### ISSUE TITLE
Can I use your kernel in Spanish?

### ISSUE THREAD

**Issue by rdpulgar** [DanielLpw/wordcloud-jieba-kmeans-tfidf#1]
Hi,

Love your code

Do you think that I can use your kernel in Spanish?

What changes do you suggest?

Thank you

**Comment by DanielLpw** [comment]
Sure，i suggest that if you want to use it in Spanish，you can use nltk instead of the function of jieba. Since jieba is only for chinese and nltk can be used in serveral languages, if there are some lib for Spanish, you can also use it.

**Comment by DanielLpw** [comment]
Sure，
i suggest that if you want to use it in Spanish，


you can use nltk instead of the function of jieba.&nbsp;


Since jieba is only for chinese and nltk can be used in serveral languages,&nbsp;


if there are some lib for Spanish to tokenize, you can also use it.


If&nbsp;useful,&nbsp; please give me a star.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DanielLpw/wordcloud-jieba-kmeans-tfidf"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月20日(星期四) 上午6:24
收件人:&nbsp;"DanielLpw/wordcloud-jieba-kmeans-tfidf"<wordcloud-jieba-kmeans-tfidf@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[DanielLpw/wordcloud-jieba-kmeans-tfidf] Can I use your kernel in Spanish? (#1)





 
Hi,
 
Love your code
 
Do you think that I can use your kernel in Spanish?
 
What changes do you suggest?
 
Thank you

**Comment by rdpulgar** [comment]
Thank you
